/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.cl_pedido;
import clases.cl_platos;
import forms.frm_reg_platos;
import clases.cl_varios;
import clases.cl_venta;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author BACA VARGAS
 */
public class frm_ver_ventas extends javax.swing.JInternalFrame {

    cl_varios c_varios = new cl_varios();
    cl_venta c_venta = new cl_venta();

    String sql;
    int fila = -1;
    String fecha = c_varios.getFechaActual();
    private String query;

    /**
     * Creates new form frm_ver_platos
     */
    public frm_ver_ventas() {
        initComponents();
        sql = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                + "inner join cliente as cl on cl.idcliente = v.idcliente "
                + "inner join empleados as em on em.idempleados = v.idempleados "
                + "where v.fecha = '" + fecha + "'";
        c_venta.mostrar(tbl_pedido, sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_bus = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_pedido = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btn_ver_detalle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_eliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_salir = new javax.swing.JButton();
        cbx_boton = new javax.swing.JComboBox<>();
        cbx_tipo = new javax.swing.JComboBox<>();

        setTitle("Ver Venta del Dia");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/find.png"))); // NOI18N
        jLabel1.setText("Buscar:");

        txt_bus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busKeyTyped(evt);
            }
        });

        tbl_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pedidoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_pedido);

        jToolBar1.setFloatable(false);

        btn_ver_detalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/application_edit.png"))); // NOI18N
        btn_ver_detalle.setText("Ver Detalle");
        btn_ver_detalle.setEnabled(false);
        btn_ver_detalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_ver_detalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_ver_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_detalleActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_ver_detalle);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/coins.png"))); // NOI18N
        jButton1.setText("Ver Cobros");
        jButton1.setEnabled(false);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator2);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/delete.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setEnabled(false);
        btn_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_eliminar);
        jToolBar1.add(jSeparator1);

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cancel.png"))); // NOI18N
        btn_salir.setText("Cerrar");
        btn_salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_salir);

        cbx_boton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POR COBRAR", "ANULADOS", "TODOS" }));
        cbx_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_botonActionPerformed(evt);
            }
        });

        cbx_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POR FECHA", "POR NRO DOCUMENTO" }));
        cbx_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_tipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbx_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_boton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ver_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_detalleActionPerformed

        if (fila > -1) {

        }
    }//GEN-LAST:event_btn_ver_detalleActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void txt_busKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String bus = txt_bus.getText();
                   
           
                int tipo_busqueda = cbx_tipo.getSelectedIndex();
                if (tipo_busqueda == 0) {
                    if (bus.length() == 10) {
                        // bus = c_varios.fecha_myql(bus);
                        query = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                                + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                                + "inner join cliente as cl on cl.idcliente = v.idcliente "
                                + "inner join empleados as em on em.idempleados = v.idempleados "
                                + "where v.fecha = '" + bus + "'";

                    } else {
                        JOptionPane.showMessageDialog(null, "Fecha no es correcta");
                        txt_bus.selectAll();
                        txt_bus.requestFocus();
                    }
                }

                if (tipo_busqueda == 1) {
                    query = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                                + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                                + "inner join cliente as cl on cl.idcliente = v.idcliente "
                                + "inner join empleados as em on em.idempleados = v.idempleados "
                            + "where v.numero = '" + bus + "' ";
                          
                }
                c_venta.mostrar(tbl_pedido, query);
                txt_bus.setText("");
     

         
        }
    }//GEN-LAST:event_txt_busKeyPressed

    private void txt_busKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyReleased

    }//GEN-LAST:event_txt_busKeyReleased

    private void txt_busKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busKeyTyped
        // TODO add your handling code here:
        //        String buscar = txt_bus.getText();
        //        String query = "select id_cliente, documento, nombre, ventas, pagado "
        //        + "from clientes "
        //        + "where (documento like '%" + buscar + "%' or nombre like '%" + buscar + "%' or id_cliente = '" + buscar + "') and id_zona = '" + id_zona + "' "
        //        + "order by nombre asc";
        //        c_cliente.ver_clientes(t_clientes, query);
    }//GEN-LAST:event_txt_busKeyTyped

    private void tbl_pedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pedidoMouseClicked
        // TODO add your handling code here:
        fila = tbl_pedido.getSelectedRow();
        btn_ver_detalle.setEnabled(true);
    }//GEN-LAST:event_tbl_pedidoMouseClicked

    private void cbx_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_botonActionPerformed
        int pedido = cbx_boton.getSelectedIndex();
        // POR COBRAR
        if (pedido == 0) {
            query = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                    + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                    + "inner join cliente as cl on cl.idcliente = v.idcliente "
                    + "inner join empleados as em on em.idempleados = v.idempleados "
                    + "where v.estado = '2'";
        }
        // ANULADOS
        if (pedido == 1) {
            query = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                    + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                    + "inner join cliente as cl on cl.idcliente = v.idcliente "
                    + "inner join empleados as em on em.idempleados = v.idempleados "
                    + "where v.estado = '3'";

        }
        // TODOS
        if (pedido == 2) {
            query = "select v.idventa, v.fecha, ds.abreviatura, v.serie, v.numero, v.idmesa, cl.nombre, em.usuario, v.estado, v.total, v.idpedido from venta as v "
                    + "inner join documento_sunat as ds on ds.idcomprobante = v.idcomprobante "
                    + "inner join cliente as cl on cl.idcliente = v.idcliente "
                    + "inner join empleados as em on em.idempleados = v.idempleados ";
        }
        c_venta.mostrar(tbl_pedido, query);
    }//GEN-LAST:event_cbx_botonActionPerformed

    private void cbx_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_tipoActionPerformed
        
    }//GEN-LAST:event_cbx_tipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_ver_detalle;
    private javax.swing.JComboBox<String> cbx_boton;
    private javax.swing.JComboBox<String> cbx_tipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbl_pedido;
    private javax.swing.JTextField txt_bus;
    // End of variables declaration//GEN-END:variables
}
